backend:
  name: github
  repo: rishi-sevakula/qi-documentation
  branch: main
  auth_endpoint: https://auth.decapcms.org/auth

site_url: https://qi-documentation.vercel.app

media_folder: static/img
public_folder: /img

collections:
  - name: docs
    label: Docs
    folder: docs
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }